const blogPosts = [
  {
    title: "The Role of Social Media in Modern Brand Growth",
    date: "December 12, 2024",
    image: "/images/blogs/blog1.png",
    category: "Social Media",
    link: "/blog/social-media-brand-growth",
  },
  {
    title: "10 Proven Strategies to Boost Your Website's SEO Rankings",
    date: "December 12, 2024",
    image: "/images/blogs/blog2.png",
    category: "SEO",
    link: "/blog/seo-strategies",
  },
  {
    title: "How Automation Can Save Your Business Hours Each Week",
    date: "December 12, 2024",
    image: "/images/blogs/blog3.png",
    category: "Automations",
    link: "/blog/automation-save-hours",
  },
  {
    title: "5 Essential Tasks a Virtual Assistant Can Handle for You",
    date: "November 12, 2024",
    image: "/images/blogs/blog4.png",
    category: "Virtual Assistant",
    link: "/blog/virtual-assistant-tasks",
  },
  {
    title: "Top Web Design Trends to Watch in 2024 - Inspiration Design",
    date: "November 02, 2024",
    image: "/images/blogs/blog5.png",
    category: "Website Designer",
    link: "/blog/web-design-trends-2024",
  },
  {
    title: "Understanding Local SEO: The Key to Attracting Nearby Customers",
    date: "October 24, 2024",
    image: "/images/blogs/blog6.png",
    category: "SEO",
    link: "/blog/local-seo-key",
  },
  {
    title: "Streamline Your Workflow with These Top Automation Tools",
    date: "October 12, 2024",
    image: "/images/blogs/blog7.png",
    category: "Automations",
    link: "/blog/automation-tools",
  },
  {
    title: "Creating a Social Media Calendar That Actually Works",
    date: "October 08, 2024",
    image: "/images/blogs/blog8.png",
    category: "Social Media",
    link: "/blog/social-media-calendar",
  },
  {
    title: "Why a Professionally Designed Website is Essential for Business",
    date: "October 02, 2024",
    image: "/images/blogs/blog9.png",
    category: "Website Designer",
    link: "/blog/professional-website-design",
  },
  {
    title: "How Automation Can Save Your Business Hours Each Week",
    date: "December 12, 2024",
    image: "/images/blogs/blog3.png",
    category: "Automations",
    link: "/blog/automation-save-hours",
  },
  {
    title: "5 Essential Tasks a Virtual Assistant Can Handle for You",
    date: "November 12, 2024",
    image: "/images/blogs/blog4.png",
    category: "Virtual Assistant",
    link: "/blog/virtual-assistant-tasks",
  },
  {
    title: "Top Web Design Trends to Watch in 2024 - Inspiration Design",
    date: "November 02, 2024",
    image: "/images/blogs/blog5.png",
    category: "Website Designer",
    link: "/blog/web-design-trends-2024",
  },
];
export default blogPosts;